# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 07:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='civil_status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gsis_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gsis_no',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Numbers are only, up to 12 digits allowed.', regex='[0-9]')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Format: '+639999999999, 09999999999, 0744449999'. Up to 13 digits allowed.", regex='^(?:\\+?63)?[09]\\d{9,12}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pagibig_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pagibig_no',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Numbers are only, up to 12 digits allowed.', regex='[0-9]')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='philhealth_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='philhealth_no',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Numbers are only, up to 12 digits allowed.', regex='[0-9]')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sss_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sss_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Numbers are only, up to 12 digits allowed.', regex='[0-9]')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel_no',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Format: '+639999999999, 09999999999, 0744449999'. Up to 13 digits allowed.", regex='^(?:\\+?63)?[09]\\d{9,12}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='tin_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tin_no',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Numbers are only, up to 12 digits allowed.', regex='[0-9]')]),
        ),
    ]
