# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161126_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
